deployment:
  tasks:
    # مسیر پروژه روی هاست
    - export DEPLOY_DIR=/home/h330619/padidehbaran
    - cd $DEPLOY_DIR

    # نصب Composer
    - /usr/local/bin/composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

    # اجرای Migration
    - php artisan migrate --force

    # ایجاد Storage Link
    - php artisan storage:link --force

    # Cache ها
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

    # دسترسی‌ها
    - chmod -R 775 storage bootstrap/cache || true
