# .cpanel.yml
deployment:
  tasks:
    # مسیر پروژه روی cPanel
    - export DEPLOY_DIR=/home/h330619/laravel
    - cd $DEPLOY_DIR

    # 🔹 Backup فایل .env اگر قبلاً وجود دارد
    - if [ -f ".env" ]; then cp .env .env.backup; fi

    # 🔹 آماده کردن فایل .env در صورت نبود
    - if [ ! -f ".env" ]; then cp .env.example .env; fi

    # 🔹 نصب پکیج‌های PHP
    - /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader

    # 🔹 نصب پکیج‌های Node.js و build فرانت‌اند
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build

    # 🔹 اجرای migration دیتابیس
    - /usr/local/bin/php artisan migrate --force

    # 🔹 اجرای seed (در صورت نیاز)
    # - /usr/local/bin/php artisan db:seed --force

    # 🔹 دادن دسترسی‌ها به پوشه‌های storage و bootstrap/cache
    - chmod -R 775 storage bootstrap/cache
    - chown -R $USER:$USER storage bootstrap/cache

    # 🔹 پاکسازی cache‌ها و cache config لاراول
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan view:clear

    # 🔹 آماده شدن پروژه
    - echo "✅ Laravel deployment completed successfully!"

    # 🔹 اطلاع در صورت backup .env
    - if [ -f ".env.backup" ]; then echo ".env backup saved"; fi
