deployment:
  tasks:
    - export DEPLOY_DIR=/home/h330619/padidehbaran/
    - cd $DEPLOY_DIR
    - /usr/local/bin/composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
    - php artisan migrate --force
    - php artisan storage:link --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - chmod -R 775 storage bootstrap/cache || true




