# .cpanel.yml
deployment:
  tasks:
    # مسیر پروژه
    - export DEPLOY_DIR=/home/h330619/laravel
    - cd $DEPLOY_DIR

    # اطمینان از اینکه .env وجود دارد
    - if [ ! -f ".env" ]; then cp .env.example .env; fi

    # نصب پکیج‌های PHP
    - /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader

    # نصب پکیج‌های JS و build فرانت‌اند
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build

    # اجرای migration و seed در صورت نیاز
    - /usr/local/bin/php artisan migrate --force
    # - /usr/local/bin/php artisan db:seed --force  # در صورت نیاز فعال کنید

    # دادن دسترسی‌ها
    - chmod -R 775 storage bootstrap/cache
    - chown -R $USER:$USER storage bootstrap/cache

    # پاکسازی کش‌ها (اختیاری ولی توصیه می‌شود)
    - /usr/local/bin/php artisan config:clear
    - /usr/local/bin/php artisan cache:clear
    - /usr/local/bin/php artisan route:clear
    - /usr/local/bin/php artisan view:clear

    # آماده شدن پروژه
    - echo "✅ Laravel deployment completed successfully!"
