---
deployment:
  tasks:
    # مسیر ریپو روی هاست
    - export DEPLOY_DIR=/home/h330619/padidehbaran
    - cd $DEPLOY_DIR

    # اطمینان از وجود .env
    - if [ ! -f ".env" ]; then cp .env.example .env; fi

    # نصب پکیج‌های PHP با Composer
    - /usr/local/bin/composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

    # Migration دیتابیس (با force چون بدون prompt اجرا میشه)
    - php artisan migrate --force

    # لینک storage
    - php artisan storage:link --force

    # کش‌ها
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

    # دسترسی‌ها
    - chmod -R 775 storage bootstrap/cache || true
