name: Laravel Minimal Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_mysql, tokenizer, xml, curl, openssl

      # 3️⃣ Install Composer
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      # 4️⃣ Install Composer dependencies
      - name: Install Composer dependencies
        run: php -d memory_limit=-1 /usr/local/bin/composer install --no-dev --optimize-autoloader

      # 5️⃣ Prepare .env if it doesn't exist
      - name: Copy .env
        run: cp .env.example .env || echo ".env already exists"

      # 6️⃣ Deploy vendor folder via FTP
      - name: Deploy vendor to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.padidehbaran.ir
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./vendor/
          server-dir: /vendor/
          security: loose
          timeout: 1800

      # 7️⃣ Deploy composer.json, composer.lock and .env separately
      - name: Deploy composer.json, composer.lock and .env
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.padidehbaran.ir
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /
          security: loose
          timeout: 190000
          exclude: |
            app/
            bootstrap/
            config/
            database/
            node_modules/
            public/
            resources/
            routes/
            storage/
            tests/
            .github/
            .git/
            vendor/
