name: Laravel FTP Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_mysql, tokenizer, xml, curl, openssl

      # 3️⃣ Install Composer
      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      # 4️⃣ Install Composer dependencies
      - name: Install Composer dependencies
        run: php -d memory_limit=-1 /usr/local/bin/composer install --no-dev --optimize-autoloader

      # 5️⃣ Setup Node.js and build assets
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build frontend assets
        run: |
          npm install
          npm run build   # اگر اسکریپت build ندارید، npm run prod بگذارید

      # 6️⃣ Prepare .env and app key
      - name: Prepare .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      # 7️⃣ Optimize Laravel
      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # 8️⃣ Deploy via FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.padidehbaran.ir
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          server-dir: /padidehbaran/
          security: loose
          timeout: 1800
          exclude: |
            node_modules/
            tests/
            .github/
            .git/
            .gitignore
            storage/logs/
