# .github/workflows/deploy.yml
name: Laravel Full Deploy

on:
  push:
    branches:
      - main  # وقتی push روی main شد اجرا شود

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ دریافت کد پروژه
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ تنظیم PHP و نصب اکستنشن‌ها
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl, json
          ini-values: post_max_size=256M, upload_max_filesize=256M

      # 3️⃣ بررسی و آماده‌سازی فایل .env
      - name: Prepare .env
        run: |
          if [ ! -f ".env" ]; then
            cp .env.example .env
            echo ".env file created from .env.example"
          fi

      # 4️⃣ نصب پکیج‌های PHP
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      # 5️⃣ تنظیم Node.js و نصب پکیج‌ها
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      # 6️⃣ اجرای migration دیتابیس
      - name: Run Laravel migrations
        run: php artisan migrate --force

      # 7️⃣ دادن دسترسی‌ها
      - name: Set permissions
        run: chmod -R 775 storage bootstrap/cache

      # 8️⃣ پاکسازی کش‌ها
      - name: Clear caches
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear

      - name: Deployment complete
        run: echo "✅ Laravel deployment completed successfully!"
