name: Laravel Minimal FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo_mysql, tokenizer, xml, curl, openssl

      # 3️⃣ Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4️⃣ Prepare .env if it doesn't exist
      - name: Prepare .env
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
            echo ".env created from .env.example"
          else
            echo ".env already exists"
          fi

        # 5️⃣ Generate APP_KEY
      - name: Generate APP_KEY
        run: php artisan key:generate --force

      # 6️⃣ Copy storage contents to public/storage
      - name: Prepare storage for public
        run: |
          mkdir -p public/storage
          rsync -a storage/app/public/ public/storage/

      # 7️⃣ Optimize Laravel
      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # 8️⃣ Deploy to FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          security: loose
          local-dir: ./
          server-dir: /
          timeout: 300000
          exclude: |
            app/**
            **/bootstrap/**
            **/node_modules/**
            **/routes/**
            **/tests/**
            **/.github/**
            **/.git/**
            **/vendor/**
            **/storage/framework/views/**
