name: Laravel FTP Deployment

on:
  push:
    branches:
      - main   # هر بار Push روی main اجرا شود

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ گرفتن کدها
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ نصب PHP و اکستنشن‌ها
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # نسخه PHP مناسب پروژه
          extensions: mbstring, bcmath, intl, pdo_mysql, tokenizer, xml

      # 3️⃣ نصب Composer و پکیج‌ها
      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      # 4️⃣ نصب Node.js و build assets (اگر داری)
      - name: Build frontend assets
        run: |
          npm install
          npm run prod

      # 5️⃣ ایجاد فایل env
      - name: Prepare .env
        run: cp .env.example .env

      # 6️⃣ تولید Laravel key
      - name: Generate app key
        run: php artisan key:generate

      # 7️⃣ پاکسازی و cache کردن Laravel
      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # 8️⃣ آپلود همه فایل‌ها روی هاست از طریق FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.padidehbaran.ir
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./           # کل پروژه لاراول آماده شده
          server-dir: /padidehbaran
          git-ftp-args: --insecure
